#!/usr/bin/env python3
"""
Build prototype/items.js from the local wiki dump (no network access).

One entry per distinct item name, with just the fields the prototype uses for
autocomplete and grading. Written as a JS file (window.ITEMS = [...]) rather than JSON
so prototype/index.html works when opened straight from disk (file://).

Usage: python3 scripts/build_prototype_data.py
"""

import json
import re
from pathlib import Path

ITEMS_PATH = Path("data/wiki/infobox_item.json")
BONUSES_PATH = Path("data/wiki/infobox_bonuses.json")
OUT_PATH = Path("prototype/items.js")


def flag(row, field):
    # Bucket stores true as "" and leaves false fields out entirely.
    return field in row


def release_year(row):
    m = re.search(r"\b(19|20)\d\d\b", row.get("release_date", ""))
    return int(m.group(0)) if m else None


def best_rows(items):
    """Pick one row per item_name: {name: row}.

    Several rows can share a name (variants, LMS copies, per-clue pages). Prefer the row
    whose page is named after the item, then the default version, then the earliest.
    """
    best = {}
    for r in items:
        name = r.get("item_name")
        if not name:
            continue
        rank = (r.get("page_name") != name, not flag(r, "default_version"), release_year(r) or 9999)
        if name not in best or rank < best[name][0]:
            best[name] = rank, r
    return {name: r for name, (_, r) in best.items()}


def main():
    items = json.loads(ITEMS_PATH.read_text(encoding="utf-8"))
    bonuses = json.loads(BONUSES_PATH.read_text(encoding="utf-8"))
    slots = {(b.get("page_name"), b.get("page_name_sub")): b for b in bonuses}

    rows = []
    for name, r in sorted(best_rows(items).items(), key=lambda kv: kv[0].lower()):
        b = slots.get((r.get("page_name"), r.get("page_name_sub"))) or {}
        quest = r.get("quest", "No")
        rows.append({
            "n": name,
            "m": flag(r, "is_members_only"),
            "t": flag(r, "tradeable"),
            "y": release_year(r),
            "v": r.get("value"),
            "w": r.get("weight"),
            "q": bool(quest) and quest != "No",
            "s": b.get("equipment_slot"),
            "c": b.get("combat_style"),
        })
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(
        "// Generated by scripts/build_prototype_data.py from OSRS Wiki data (CC BY-NC-SA 3.0).\n"
        "window.ITEMS = " + json.dumps(rows, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(rows)} items to {OUT_PATH} ({OUT_PATH.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
