#!/usr/bin/env python3
"""
Randomly pick daily answers from the local item data (no network access).

Picks --days distinct items starting at --start, one per day, from every distinct item
name in data/wiki/infobox_item.json that has an image. No filtering yet; see
docs/item-pool-filtering.md for the plan.

By default this only prints the selection. Every run prints the seed it used, so a
selection you like can be reproduced exactly and saved:

  python3 scripts/pick_schedule.py --start 2026-10-06 --days 7
  python3 scripts/pick_schedule.py --start 2026-10-06 --days 7 --seed 12345 --write

To keep some days and reroll the rest, pin the ones to keep (repeatable):

  python3 scripts/pick_schedule.py --start 2026-10-06 --pin "2026-10-06=Burnt karambwan"

--write saves prototype/schedule.js, which the game reads. The images still have to be
downloaded with fetch_item_image.py (one run per item; wiki requests need sign-off).
The printed fetch commands use the page_name, which picks the same row the game uses.
"""

import argparse
import json
import random
import secrets
import shlex
import sys
from datetime import date, timedelta
from pathlib import Path

from build_prototype_data import ITEMS_PATH, best_rows
from fetch_item_image import detail_title, local_basename

OUT_PATH = Path("prototype/schedule.js")
IMAGE_DIR = "data/images"   # where fetch_item_image.py saves, relative to the repo root


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--start", type=date.fromisoformat, default=date.today(),
                   help="first date, YYYY-MM-DD (default: today)")
    p.add_argument("--days", type=int, default=7, help="number of days to schedule (default: 7)")
    p.add_argument("--seed", type=int, help="random seed (default: a new random one, printed)")
    p.add_argument("--pin", action="append", default=[], metavar="DATE=ITEM",
                   help="fix the answer for a date; other days are picked at random (repeatable)")
    p.add_argument("--write", action="store_true", help=f"save the selection to {OUT_PATH}")
    args = p.parse_args()

    seed = args.seed if args.seed is not None else secrets.randbelow(10**9)
    rng = random.Random(seed)

    rows = best_rows(json.loads(ITEMS_PATH.read_text(encoding="utf-8")))
    pool = sorted(name for name, r in rows.items() if r.get("image"))
    dates = [(args.start + timedelta(days=i)).isoformat() for i in range(args.days)]

    pins = {}
    for pin in args.pin:
        d, sep, name = pin.partition("=")
        d, name = d.strip(), name.strip()
        if not sep or d not in dates:
            p.error(f"--pin {pin!r}: expected DATE=ITEM with a date in {dates[0]}..{dates[-1]}")
        if name not in pool:
            p.error(f"--pin {pin!r}: no item named {name!r} with an image")
        pins[d] = name
    if len(set(pins.values())) < len(pins):
        p.error("--pin: the same item is pinned to more than one date")

    unpinned = [d for d in dates if d not in pins]
    random_picks = iter(rng.sample([n for n in pool if n not in pins.values()], len(unpinned)))
    picks = [pins[d] if d in pins else next(random_picks) for d in dates]

    schedule = []
    for i, name in enumerate(picks):
        r = rows[name]
        detail = detail_title(r["image"][0])
        schedule.append({
            "date": dates[i],
            "answer": name,
            "page": r.get("page_name_sub") or r.get("page_name"),   # what fetch_item_image.py --page matches first
            "image": f"../{IMAGE_DIR}/{local_basename(detail)}.png",   # relative to prototype/
            "source": "https://oldschool.runescape.wiki/w/" + detail.replace(" ", "_"),
        })

    print(f"Pool: {len(pool)} item names with an image. Seed: {seed}\n")
    for e in schedule:
        print(f"{e['date']}  {e['answer']}" + ("   (pinned)" if e["date"] in pins else ""))
        print(f"            page:  {e['page']}")
        print(f"            image: {e['source']}")
    print("\nFetch commands (each makes wiki requests; run only with sign-off):")
    for e in schedule:
        print(f"  python3 scripts/fetch_item_image.py --contact \"<contact>\" --page {json.dumps(e['page'])}")

    if args.write:
        OUT_PATH.write_text(
            f"// Generated by scripts/pick_schedule.py (seed {seed}). To reproduce:\n"
            f"//   python3 {shlex.join(sys.argv)}\n"
            "window.SCHEDULE = " + json.dumps(schedule, ensure_ascii=False, indent=1) + ";\n",
            encoding="utf-8",
        )
        print(f"\nWrote {OUT_PATH}")
    else:
        pin_args = "".join(f" --pin {json.dumps(f'{d}={n}')}" for d, n in pins.items())
        print(f"\nNot saved. To save exactly this selection, rerun with:{pin_args} --seed {seed} --write")


if __name__ == "__main__":
    main()
