// Generated by scripts/pick_schedule.py (seed 435254318). To reproduce:
//   python3 scripts/pick_schedule.py --start 2026-10-06 --days 7 --pin '2026-10-06=Burnt karambwan' --pin '2026-10-08=Twisted steel trophy' --pin 2026-10-09=Purplefin --pin '2026-10-11=Bronze battleaxe' --pin '2026-10-12=Adamant gloves' --seed 435254318 --write
window.SCHEDULE = [
 {
  "date": "2026-10-06",
  "answer": "Burnt karambwan",
  "page": "Burnt karambwan",
  "image": "../data/images/Burnt_karambwan_detail.png",
  "source": "https://oldschool.runescape.wiki/w/File:Burnt_karambwan_detail.png"
 },
 {
  "date": "2026-10-07",
  "answer": "Pressure gauge",
  "page": "Pressure gauge",
  "image": "../data/images/Pressure_gauge_detail.png",
  "source": "https://oldschool.runescape.wiki/w/File:Pressure_gauge_detail.png"
 },
 {
  "date": "2026-10-08",
  "answer": "Twisted steel trophy",
  "page": "Twisted steel trophy",
  "image": "../data/images/Twisted_steel_trophy_detail.png",
  "source": "https://oldschool.runescape.wiki/w/File:Twisted_steel_trophy_detail.png"
 },
 {
  "date": "2026-10-09",
  "answer": "Purplefin",
  "page": "Purplefin",
  "image": "../data/images/Purplefin_detail.png",
  "source": "https://oldschool.runescape.wiki/w/File:Purplefin_detail.png"
 },
 {
  "date": "2026-10-10",
  "answer": "Oil lamp",
  "page": "Oil lamp#Unlit",
  "image": "../data/images/Oil_lamp_detail.png",
  "source": "https://oldschool.runescape.wiki/w/File:Oil_lamp_detail.png"
 },
 {
  "date": "2026-10-11",
  "answer": "Bronze battleaxe",
  "page": "Bronze battleaxe",
  "image": "../data/images/Bronze_battleaxe_detail.png",
  "source": "https://oldschool.runescape.wiki/w/File:Bronze_battleaxe_detail.png"
 },
 {
  "date": "2026-10-12",
  "answer": "Adamant gloves",
  "page": "Adamant gloves",
  "image": "../data/images/Adamant_gloves_detail.png",
  "source": "https://oldschool.runescape.wiki/w/File:Adamant_gloves_detail.png"
 }
];
